name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Prepare Firebase credentials (optional)
        id: prepare-firebase
        run: |
          # If a service account JSON is provided as a secret, write it to disk for the GCP auth step.
          if [ -n "$FIREBASE_SERVICE_ACCOUNT" ]; then
            echo "$FIREBASE_SERVICE_ACCOUNT" > ${GITHUB_WORKSPACE}/firebase-service-account.json
            echo "service-account-written=true" >> $GITHUB_OUTPUT || true
          else
            echo "service-account-written=false" >> $GITHUB_OUTPUT || true
          fi

      - name: Install Firebase CLI
        run: npm install -g firebase-tools@latest

      - name: Authenticate to GCP using service account
        if: ${{ secrets.FIREBASE_SERVICE_ACCOUNT != '' }}
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

      - name: Deploy to Firebase (service account)
        if: ${{ secrets.FIREBASE_SERVICE_ACCOUNT != '' }}
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        run: |
          echo "Deploying with service account to project: $FIREBASE_PROJECT_ID"
          firebase deploy --only hosting --project "$FIREBASE_PROJECT_ID"

      - name: Deploy to Firebase (token fallback)
        if: ${{ secrets.FIREBASE_SERVICE_ACCOUNT == '' }}
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
        run: |
          if [ -z "$FIREBASE_CLI_TOKEN" ]; then
            echo "Neither FIREBASE_SERVICE_ACCOUNT nor FIREBASE_CLI_TOKEN is set. Exiting." >&2
            exit 1
          fi
          echo "Deploying with CLI token to project: $FIREBASE_PROJECT_ID"
          firebase deploy --only hosting --project "$FIREBASE_PROJECT_ID" --token "$FIREBASE_CLI_TOKEN"

      # Note: This workflow expects either:
      # - A pre-created service account JSON in the FIREBASE_SERVICE_ACCOUNT secret and FIREBASE_PROJECT_ID set,
      # OR
      # - A CI token produced by `firebase login:ci` stored in FIREBASE_CLI_TOKEN and FIREBASE_PROJECT_ID set.
